linters-settings:
  custom:
    testsnake:
      path: ./testsnake.so
      description: Checks that test function names follow snake_case convention
      original-url: github.com/yayoc/test-snake

linters:
  enable:
    - testsnake
