version: 2

project_name: testsnake

builds:
  - id: testsnake
    main: ./cmd/testsnake
    binary: testsnake

release:
  github:
    owner: yayoc
    name: testsnake
  draft: false
  prerelease: auto

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
